export enum EMensagem {
  DeveSerInformado = 'Deve ser informado',
  DeveSerVazio = 'Deve ser vazio',
  IDsDiferentes = 'Os IDs informados são diferentes',
  ImpossivelAlterar = 'Impossível alterar o cadastro',
  ImpossivelDesativar = 'Impossivel desativar o cadastro',
  NaoPodeSerVazio = 'Não pode ser vazio',
  NaoValido = 'Não válido',
  MaisCaracteresQuePermitido = 'Possui mais caracteres que o permitido',
  ImpossivelCadastrar = 'Impossível realizar o cadastro',
  AtualizadoSucesso = 'Atualizado com sucesso',
  DesativadoSucesso = 'Desativado com sucesso',
  ExcluidoSucesso = 'Excluído com sucesso',
  FilterInvalido = 'Filter inválido',
  OrderInvalido = 'Order inválido',
  SalvoSucesso = 'Salvo com sucesso',
  AutenticadoSucesso = 'Autenticado com sucesso',
  UsuarioSenhaInvalido = 'Usuario e/ou senha inválidos',
}
